Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,15 +24,20 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: "20"
+          cache: "pnpm"
 
-      - name: Install pnpm
-        run: npm install -g pnpm
+      - name: Install PNPM
+        run: corepack enable && corepack prepare pnpm@latest --activate
 
       - name: Install dependencies
-        run: pnpm install
+        run: pnpm install --frozen-lockfile
 
       - name: Build the project
         run: pnpm build
+
+      - name: Verify Build Output
+        run: |
+          ls -la dist || echo "dist folder is missing!"
 
       - name: Install Playwright Browsers
         run: |
@@ -83,6 +88,6 @@ jobs:
           ls -la dist    
 
       - name: Deploy to GitHub Pages
-        run: pnpm deploy
+        run: pnpm --filter . deploy
         env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }} # This token is provided automatically by GitHub Actions
